version: "3.8"
services:
  backend:
    build: ./backend
    image: hsdem/boti-exam-backend:latest
    container_name: backend
    ports:
      - "8000:8000"
    environment:
      - DEBUG=0

  frontend:
    build: ./frontend
    image: hsdem/boti-exam-frontend:latest
    container_name: frontend
    ports:
      - "3000:80"
