# Generated by Django 5.1.2 on 2024-11-26 23:05

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Plan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('price', models.CharField(max_length=10)),
                ('bots', models.CharField(max_length=50)),
                ('memory', models.CharField(max_length=50)),
                ('messages', models.CharField(max_length=50)),
                ('features', models.TextField()),
                ('selected', models.CharField(choices=[('yes', 'Selected'), ('no', 'Not Selected'), ('dev', 'Development Plan')], default='no', max_length=10)),
            ],
        ),
    ]
